# Site settings
title: linkarys
email: linkarys@gmail.com
description: > # Hi, nice to see you.

# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title

# baseurl: "http://linkarys.github.io/" # the subpath of your site, e.g. /blog/
# url: "http://linkarys.github.io/" # the base hostname & protocol for your site
github_username:  linkarys

