# Site settings
title: linkarys
email: linkarys@gmail.com
description: > # Hi, nice to see you.
# baseurl: "http://linkarys.github.io/" # the subpath of your site, e.g. /blog/
# url: "http://linkarys.github.io/" # the base hostname & protocol for your site
github_username:  linkarys

# Build settings
markdown: kramdown
