# Site settings
title: linkarys
email: linkarys@gmail.com
description: > # Hi, nice to see you.

# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title

# baseurl: "http://linkarys.github.io/" # the subpath of your site, e.g. /blog/
# url: "http://linkarys.github.io/" # the base hostname & protocol for your site
github_username:  linkarys

# Conversion
markdown:    kramdown
# highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: [fenced_code_blocks]
  # extensions: [no_fenced_code_blocks]
  render_options:

kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

highlighter: rouge

comments:
  disqus:
    shortname: linkarys

# Pagination
paginate: 3
paginate_path: /page/:num

# Serving
detach:  false
port:    4001
host:    127.0.0.1
baseurl: "" # does not include hostname

# Highlight
# redcarpet:
#   extensions: [fenced_code_blocks]

# Collections
collections:
    javascript:
      path: "javascripts"
      output: true
    styles:
      output: true

# Default options
defaults:
  -
    scope:
      path: ""
    values:
      author: linkarys
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: ['untaged']
  -
    scope:
      path: "javascript"
    values:
      layout: "post"
      tags: ['untaged']

# Navs
navs:
  - title: Javascript
    url: /javascript
  - title: CSS
    url: /css
  # - title: Archives
  #   url: /archives
  # - title: 关于我
  #   url: /contact
  # - title: 友情链接
  #   url: /links

